package io.github.rosemoe.editor.core.analyze.signal;

public enum Routes {

    // Non endpoint specific keywords
    BEGIN, END,
    // End points
    ACTION_CONTENT_ACTION_STACK,
    ACTION_CONTENT_SELECT_ALL,
    ACTION_CONTENT_COPY,
    ACTION_UNDO,
    ACTION_REDO, ACTION_CONTENT_CUT, ACTION_CONTENT_PASTE, ACTION_CURSOR_DOWN, ACTION_CURSOR_LEFT, ACTION_CURSOR_UP, ACTION_CURSOR_RIGHT, ACTION_CURSOR_END, ACTION_CURSOR_HOME, ACTION_CURSOR_PAGE_DOWN, ACTION_CURSOR_PAGE_UP, RIGHT, LEFT, UP, DOWN, ACTION_CURSOR, PAGE_UP, PAGE_HOME, HOME, PAGE_DOWN, ACTION_CONTENT_TEXT, ACTION_CONTENT_TEXT_DEL, ACTION_CONTENT_TEXT_DEL_FORWARD, ACTION_CONTENT_TEXT_TAB, ACTION_CONTENT_TEXT_SPACE, ACTION_CONTENT_TEXT_ENTER, ACTION_BACK, ACTION_EDIT_BATCH,
}
